### ISSUE TITLE
Shortcut

### ISSUE THREAD

**Issue by descobal** [Atim33/autopdfexporter-sketch-plugin#2]
How do I create a keyboard shortcut for this? I'm in the Keyboard Shortcuts menu in settings and when I type in the Menu Title, Sketch isn't recognizing it. Is there something I'm doing wrong? This is what I'm using.

✂️Auto-export all '[S]' Prefix Artboards to PDF

**Comment by bvmensvoort** [comment]
It was cmd+p, but it looks like it is overridden by Sketch.
When changing it to cmd+shift+p, it is reconnected to the plugin. You can work with it in [pull request #5](https://github.com/Atim33/autopdfexporter-sketch-plugin/pull/5).

**Comment by Atim33** [comment]
fixed. thanks

ctrl cmd p
