### ISSUE TITLE
Plug-in doesn't work correctly on Sketch Version 60 (88103)

### ISSUE THREAD

**Issue by graphixkid** [Atim33/autopdfexporter-sketch-plugin#3]
Hi - 

I LOVE this plug-in!!! Unfortunately, it stopped working properly when I updated to Sketch Version 60 (88103). 

Now, when I execute the plug-in, it creates slices in the sidebar layer list.

**Comment by bvmensvoort** [comment]
Yes, it is a very handy plugin!
I did a fix to prevent the crash on Sketch 61. Hopefully this will fix the new slices as well. You can find it as [pull request #4](https://github.com/Atim33/autopdfexporter-sketch-plugin/pull/4).

**Comment by Atim33** [comment]
Fix is going out today. thanks
